version: "3.3"

services:
  postgres:
    image: postgres
    environment: &postgres_env
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./postgres/mount:/var/lib/postgresql/data
  server:
    build: .
    command: hypercorn --bind 0.0.0.0:8000 src.api.main:app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      <<: *postgres_env
      POSTGRES_URL: $POSTGRES_URL
      IPFS_URL: $IPFS_URL
      SECRET_KEY: $SECRET_KEY
      ALGORITHM: $ALGORITHM
      ACCESS_TOKEN_EXPIRE_MINUTES: $ACCESS_TOKEN_EXPIRE_MINUTES
  ipfs:
    image: ipfs/go-ipfs:v0.7.0
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
    volumes:
      - ./ipfs/data:/ipfs/data
      - ./ipfs/export:/ipfs/export
